name: Classroom CI-CD Demo 2026

# ה-Pipeline יופעל אוטומטית בכל פעם שמבצעים Push לענף הראשי (main)
on:
  push:
    branches: [ main ]

jobs:


  # שלב 1: בנייה (Build)
  build_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Simulate Build
        run: |
          echo "=== STARTING BUILD STAGE ==="
          echo "Installing application dependencies..."
          echo "Compiling and packaging the code..."
          echo "Build finished successfully!"

  # שלב 2: בדיקות (Test) - ירוץ רק אם שלב הבנייה הצליח
  test_stage:
    needs: build_stage
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Tests
        run: |
          echo "=== STARTING TEST STAGE ==="
          echo "Running Automated Unit Tests..."
          # פקודת פייתון פשוטה שמדמה בדיקה שעוברת בהצלחה
          python3 -c "print('JUnit / PyTest status: 100% Success!')"

  # שלב 3: פריסה (Deploy) - ירוץ רק אם שלב הבדיקות הצליח
  deploy_stage:
    needs: test_stage
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Deploy
        run: |
          echo "=== STARTING DEPLOY STAGE ==="
          echo "Deploying the artifact to Staging environment..."
          echo "Deployment completed! App is live."
